# Generated by Django 5.2 on 2025-04-13 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_project_amount_raised_remove_project_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="amount_raised",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(default="2025-12-31"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
