# Generated by Django 5.2 on 2025-04-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_project_amount_raised_project_end_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
