# Generated by Django 5.2 on 2025-04-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="username",
            field=models.CharField(
                default=0.0002717391304347826, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
