# Generated by Django 5.2 on 2025-04-24 01:21

import charities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0005_alter_charityproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=charities.models.project_image_path),
        ),
    ]
