# Generated by Django 5.2 on 2025-04-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0006_alter_charityproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='charity_images/'),
        ),
    ]
