# Generated by Django 5.2 on 2025-04-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0007_alter_charityproject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charityproject',
            name='image',
        ),
    ]
