services:
  - type: web
    name: charity-water-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health

databases:
  - name: water-charity-db
    plan: free

  - type: web
    name: charity-water-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/projects
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 