services:
  # Backend API Service
  - type: web
    name: water-charity-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production

  # Frontend Service
  - type: web
    name: water-charity-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: REACT_APP_API_URL
        value: https://water-charity-api.onrender.com

databases:
  - name: water-charity-db
    plan: free 