services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    restart: always

  django:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    restart: always

  flask:
    build:
      context: ./donations
    depends_on:
      - db
      - django
    env_file:
      - ./.env
    volumes:
      - ./donations:/app
    ports:
      - "5001:5000"
    command: gunicorn "app:create_app()" --bind 0.0.0.0:5000
    restart: always

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - django
      - flask
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
